 postgresql:
  enabled: <value>
  auth:
    username: <username>
    password: <password>
    database: <database name>
    schema: <schema name>
    DB_URL:  <database url>
    image: <docker image>
    DATABASE_URL: <database url>

  primary:
    persistence:
      enabled: true
      storageClass: <storage name>
      size: <size>
  

 webapp:
  name: <name>
  image: <docker image>

 kms_id: <enter key id>
 volumeBindingMode: <value>
 parameters: <value>
 type: <value>
 name : <name>
 provisioner: <provisioner>