apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kafka-config
  namespace: cve-processor
data:
  KAFKA_BROKER_ADDRESS: {{include "KAFKA_BROKER_ADDRESS" .}}
  KAFKA_TOPIC: {{ .Values.kafka.topic }}