apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
data:
  WEBAPP_DB_URL: {{ .Values.postgresql.auth.DATABASE_URL }}
  FLYWAY_URL: {{ .Values.postgresql.auth.DB_URL }}
  FLYWAY_USER: {{ .Values.postgresql.auth.username }}
  FLYWAY_PASSWORD: {{ .Values.postgresql.auth.password }}
  FLYWAY_SCHEMAS: {{ .Values.postgresql.auth.schema }}