apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-cve-processor
spec:
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secret
      restartPolicy: OnFailure
      initContainers:
        - name: flyway-migration
          image: {{ .Values.postgresql.auth.image }}
          command: ["flyway", "migrate"]
          env:
            - name: FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-config
                  key: FLYWAY_URL
            - name: FLYWAY_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-config
                  key: FLYWAY_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-config
                  key: FLYWAY_PASSWORD
            - name: FLYWAY_SCHEMAS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-config
                  key: FLYWAY_SCHEMAS
      containers:
        - name: {{ .Values.webapp.name }}
          image: {{ .Values.webapp.image }}
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-config
                  key: WEBAPP_DB_URL
