apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-cve-processor
  namespace: cve-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-cve-processor
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-cve-processor
    spec:
      imagePullSecrets:
        - name: {{.Release.Name}}-docker-secret
      containers:
        - name: producer
          image: {{.Values.producer.image}}
          env:
            - name: KAFKA_BROKER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-kafka-config
                  key: "KAFKA_BROKER_ADDRESS"
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-kafka-config
                  key: KAFKA_TOPIC
            - name: KAFKA_ADVERTISED_LISTENERS
              value: {{ include "KAFKA_ADVERTISED_LISTENERS" . }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
