apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: producer-role
  namespace: {{ .Values.producer.namespace }}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
