apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: producer-rolebinding
  namespace: {{ .Values.webapp.namespace }}
subjects:
  - kind: ServiceAccount
    name: producer-sa
    namespace: {{ .Values.producer.namespace }}
roleRef:
  kind: Role
  name: producer-role
  apiGroup: rbac.authorization.k8s.io
