apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
spec:
  selector:
    app: {{ .Values.database.name }}
  ports:
  - protocol: {{ .Values.database.config.protocol }}
    port: {{ .Values.database.config.port }}
    targetPort: {{ .Values.database.config.port }}