apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.name }}
provisioner: {{ .Values.provisioner }}
parameters:
  type: {{ .Values.type }} 
  encrypted: {{ .Values.parameters }}  
  kmsKeyId: {{ .Values.kms_id }}
volumeBindingMode: {{ .Values.volumeBindingMode }}
